### ISSUE TITLE
运行python脚本示例

### ISSUE THREAD

**Issue by HusterHaoYoung** [HongZhaoHua/jstarcraft-rns#2]
大佬你好，我在运行Python示例遇到了如下bug：

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper 
WARNING: Please consider reporting this to the maintainers of jnr.posix.JavaLibCHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

com.jstarcraft.core.script.exception.ScriptExpressionException: javax.script.ScriptException: com.jstarcraft.ai.data.exception.DataException: com.jstarcraft.ai.data.exception.DataException: java.lang.RuntimeException: java.lang.NullPointerException in <script> at line number 100

	at com.jstarcraft.core.script.PythonExpression.doWith(PythonExpression.java:98)
	at com.jstarcraft.rns.script.ScriptTestCase.testPython(ScriptTestCase.java:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: javax.script.ScriptException: com.jstarcraft.ai.data.exception.DataException: com.jstarcraft.ai.data.exception.DataException: java.lang.RuntimeException: java.lang.NullPointerException in <script> at line number 100
	at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:222)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:59)
	at org.python.jsr223.PyScriptEngine.access$300(PyScriptEngine.java:20)
	at org.python.jsr223.PyScriptEngine$PyCompiledScript.eval(PyScriptEngine.java:250)
	at java.scripting/javax.script.CompiledScript.eval(CompiledScript.java:103)
	at com.jstarcraft.core.script.PythonExpression.doWith(PythonExpression.java:94)
	... 23 more
Caused by: Traceback (most recent call last):
  File "<script>", line 100, in <module>
	at com.jstarcraft.ai.data.converter.StreamConverter.convert(StreamConverter.java:36)
	at com.jstarcraft.ai.data.converter.StreamConverter.convert(StreamConverter.java:20)
	at com.jstarcraft.rns.task.AbstractTask.execute(AbstractTask.java:208)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
com.jstarcraft.ai.data.exception.DataException: com.jstarcraft.ai.data.exception.DataException: java.lang.RuntimeException: java.lang.NullPointerException

	at org.python.core.Py.JavaError(Py.java:552)
	at org.python.core.Py.JavaError(Py.java:543)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:480)
	at org.python.core.PyObject.__call__(PyObject.java:484)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.f$0(<script>:110)
	at org.python.pycode._pyx0.call_function(<script>)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	... 27 more
Caused by: com.jstarcraft.ai.data.exception.DataException: java.lang.RuntimeException: java.lang.NullPointerException
	at com.jstarcraft.ai.data.converter.StreamConverter.convert(StreamConverter.java:36)
	at com.jstarcraft.ai.data.converter.StreamConverter.convert(StreamConverter.java:20)
	at com.jstarcraft.rns.task.AbstractTask.execute(AbstractTask.java:208)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)
	... 40 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.jstarcraft.ai.data.converter.CsvConverter.parseData(CsvConverter.java:73)
	at com.jstarcraft.ai.data.converter.StreamConverter.convert(StreamConverter.java:32)
	... 47 more
Caused by: java.lang.NullPointerException
	at org.apache.commons.lang3.SystemUtils.isJavaVersionAtLeast(SystemUtils.java:1642)
	at org.apache.commons.lang3.ClassUtils.isAssignable(ClassUtils.java:690)
	at org.apache.commons.lang3.reflect.TypeUtils.isAssignable(TypeUtils.java:375)
	at org.apache.commons.lang3.reflect.TypeUtils.isAssignable(TypeUtils.java:326)
	at org.apache.commons.lang3.reflect.TypeUtils.isInstance(TypeUtils.java:1104)
	at com.jstarcraft.core.common.conversion.csv.ConversionUtility.convert(ConversionUtility.java:58)
	at com.jstarcraft.ai.data.converter.CsvConverter.parseData(CsvConverter.java:55)
	... 48 more

Process finished with exit code 255
我自己经过断点调试，觉得错误发生在Python脚本的18行，即measures = task.execute()，而我没有找到这个方法的具体实现无法进一步调试，打扰大佬了，请大佬赐教

**Comment by HongZhaoHua** [comment]
你好，应该是你的配置文件(data.properties或者其它模型的properties)有问题导致数据类型无法转换导致的。
例如，CSV中的某一列实际是String类型，而配置文件却指定成int类型。

**Comment by HongZhaoHua** [comment]
在Java代码中CsvConverter的第55行代码设置断点，你就能够跟踪到问题了。
BTW：measures = task.execute()其实也有对应的Java代码，在单元测试目录的AbstractTask.execute方法。

**Comment by HongZhaoHua** [comment]
您本地的JDK版本是多少呢？有没有修改过代码或者配置？

**Comment by HusterHaoYoung** [comment]
多谢大佬指教，没有修改过代码配置，本地JDK是JAVA11 ，刚换成Java1.8跑通了，十分感谢！

**Comment by HongZhaoHua** [comment]
不必客气，那就是兼容性还有些问题。谢谢反馈。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haoyoung"<notifications@github.com&gt;; 
发送时间: 2020年1月6日(星期一) 下午5:20
收件人: "HongZhaoHua/jstarcraft-rns"<jstarcraft-rns@noreply.github.com&gt;; 
抄送: "^蟲小ヤ鬼大^"<110399057@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [HongZhaoHua/jstarcraft-rns] 运行python脚本示例 (#2)




多谢大佬指教，没有修改过代码配置，本地JDK是JAVA11 ，刚换成Java1.8跑通了，十分感谢！
